#!/bin/sh
set -e

EGRESS_CERT_DIR="${EGRESS_CERT_DIR:-/etc/egress-audit/certs}"
mkdir -p /home/mitmproxy/.mitmproxy /var/log/retinue/egress "$EGRESS_CERT_DIR"

# Wait for the CA to be generated by the retinue container. This is normally
# created automatically at first start, but if this sidecar starts first we
# need to wait rather than fail.
WAITED=0
TIMEOUT=60
while [ ! -f "$EGRESS_CERT_DIR/mitmproxy-ca.pem" ]; do
  if [ "$WAITED" -ge "$TIMEOUT" ]; then
    echo "[egress-audit] CA not generated after ${TIMEOUT}s; generating one locally as fallback." >&2
    openssl req -x509 -newkey rsa:2048 \
      -keyout "$EGRESS_CERT_DIR/egress-ca-key.pem" \
      -out "$EGRESS_CERT_DIR/egress-ca-cert.pem" \
      -days 3650 -nodes \
      -subj "/CN=Retinue Egress Audit CA/O=Retinue" \
      -addext "subjectKeyIdentifier=hash" \
      -addext "authorityKeyIdentifier=keyid:always,issuer" \
      -addext "basicConstraints=critical,CA:TRUE"
    cat "$EGRESS_CERT_DIR/egress-ca-key.pem" "$EGRESS_CERT_DIR/egress-ca-cert.pem" \
      > "$EGRESS_CERT_DIR/mitmproxy-ca.pem"
    chmod 600 "$EGRESS_CERT_DIR/mitmproxy-ca.pem" "$EGRESS_CERT_DIR/egress-ca-key.pem"
    chmod 644 "$EGRESS_CERT_DIR/egress-ca-cert.pem"
    break
  fi
  sleep 1
  WAITED=$((WAITED + 1))
done

cp "$EGRESS_CERT_DIR/mitmproxy-ca.pem" /home/mitmproxy/.mitmproxy/mitmproxy-ca.pem
chmod 600 /home/mitmproxy/.mitmproxy/mitmproxy-ca.pem
chown -R mitmproxy:mitmproxy /home/mitmproxy/.mitmproxy /var/log/retinue/egress

echo "[egress-audit] Starting mitmdump ..."
# The upstream mitmproxy image provides gosu, not su-exec.
exec gosu mitmproxy mitmdump \
  --mode regular \
  --listen-host 0.0.0.0 \
  --listen-port 8080 \
  --set block_global=false \
  --set confdir=/home/mitmproxy/.mitmproxy \
  -s /scripts/egress-audit-addon.py \
  "$@"
